select*from customer limit 20

-- Q1 What is the total reveneu generated by male vs female customer

select gender, SUM(purchase_amout) as reveneu
from customer
group by gender

-- Q2 which customer used discount but still spent more than the avg purchase amt

select customer_id , purchase_amout
from customer
where discount_applied = 'Yes' and purchase_amout >= (select AVG(purchase_amout)from customer)

-- Q3 which are the top 5 products with the highest avg review rating
select item_purchased , ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer 
group by item_purchased 
order by avg(review_rating) desc 
limit 5;

-- Q4 Compare the avg Purchase amounts between standard and express shipping

select shipping_type, ROUND(AVG(purchase_amout::numeric),2)
from customer 
where shipping_type in ('Standard', 'Express')
group by shipping_type


-- Q5 Do subscribed customer spend more? compare avg spend and total reveneu between subs and non-subs
select subscription_status , COUNT(customer_id) as total_customer, 
AVG(purchase_amout) as avg_spend,
SUM(purchase_amout) as total_reveneu
from customer
group by subscription_status
order by avg_spend, total_reveneu desc;

-- Q6 . which 5 products has highest percentages of purchases with discount applied , if 10 hats are in the db then
-- 50% means 5 hats are on discount

SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)::numeric / COUNT(*) * 100,2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Q7 segment customers into new , returning and loyal based on their total number of previous purchase and show the 
-- count of each segment

with customer_type as (
select customer_id , previous_purchases,
case 
    when previous_purchases =1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer	
)
select customer_segment , count(*) as "Number of customer"
from customer_type
group by customer_segment

--Q8 What are the top 3 most purchased products with in each catagory
with item_counts as(
select category, item_purchased , count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer 
group by category, item_purchased
)

select  item_rank , category, item_purchased, total_orders
from item_counts 
where item_rank <= 3


-- Q9  are customers who are repeat buyers (more than 5 prev purchases) also likely to subs?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- Q10 what is the reveneu contribution of each age group
select age_group,
SUM(purchase_amout) as total_reveneu
from customer
group by age_group
order by total_reveneu desc;




